export const UPDATE_PRODUCTS = "UPDATE_PRODUCTS"; // set UPDATE_PRODUCTS to UPDATE_PRODUCTS

export const ADD_TO_CART = "ADD_TO_CART"; // set ADD_TO_CART to ADD_TO_CART
export const ADD_MULTIPLE_TO_CART = "ADD_MULTIPLE_TO_CART"; // set ADD_MULTIPLE_TO_CART to ADD_MULTIPLE_TO_CART
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"; // set REMOVE_FROM_CART to REMOVE_FROM_CART
export const CLEAR_CART = "CLEAR_CART"; // set CLEAR_CART to CLEAR_CART
export const UPDATE_CART_QUANTITY = "UPDATE_CART_QUANTITY"; // set UPDATE_CART_QUANTITY to UPDATE_CART_QUANTITY
export const TOGGLE_CART = "TOGGLE_CART"; // set TOGGLE_CART to TOGGLE_CART

export const UPDATE_CATEGORIES = "UPDATE_CATEGORIES"; // set UPDATE_CATEGORIES to UPDATE_CATEGORIES
export const UPDATE_CURRENT_CATEGORY = "UPDATE_CURRENT_CATEGORY"; // set UPDATE_CURRENT_CATEGORY to UPDATE_CURRENT_CATEGORY
